" Make external commands work through a pipe instead of a pseudo-tty
"set noguipty


set ch=2		" Make command line two lines high

set mousehide		" Hide the mouse when typing text

" Make shift-insert work like in Xterm
noremap <S-Insert> <MiddleMouse>
noremap! <S-Insert> <MiddleMouse>

" Switch on syntax highlighting if it wasn't on yet.
if !exists("syntax_on")
    syntax on
endif

set background=light
set guicursor=a:blinkon0 " Disable cursor blinking
set guioptions+=c

let g:tagbar_usearrows = 1

"tab labels show the filename without path(tail) (see :help statusline for options)
":set guitablabel=%t
function GuiTabLabel()
	let label = ''
	let bufnrlist = tabpagebuflist(v:lnum)

	" Add '+' if one of the buffers in the tab page is modified
	for bufnr in bufnrlist
		if getbufvar(bufnr, "&modified")
			let label = '+'
			break
		endif
	endfor

	" Append the number of windows in the tab page if more than one
"	let wincount = tabpagewinnr(v:lnum, '$')
"	if wincount > 1
"		let label .= wincount
"	endif
	if label != ''
		let label .= ' '
	endif

	" Append the buffer name
	return label . bufname(bufnrlist[tabpagewinnr(v:lnum) - 1])
endfunction

set guitablabel=%{GuiTabLabel()}
"set guitablabel=%f
colorscheme molokai

"set the X11 font to use
set guifont=Inconsolata\ 13
